package com.easyshell.server.ai.orchestrator;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Execution plan generated by Planner agent.
 * Displayed as a todo-list in the frontend; drives plan-based execution.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ExecutionPlan {

    /** Human-readable summary of the plan */
    private String summary;

    /** Ordered list of steps to execute */
    @Builder.Default
    private List<PlanStep> steps = new ArrayList<>();

    /** Whether the plan requires user confirmation before execution */
    private boolean requiresConfirmation;

    /** Estimated risk level: LOW / MEDIUM / HIGH */
    private String estimatedRisk;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PlanStep {
        /** Step index (0-based) */
        private int index;
        /** Step description (e.g. "查询所有在线主机") */
        private String description;
        /** Which agent handles this step */
        private String agent;
        /** Step status: pending / running / completed / failed / skipped */
        @Builder.Default
        private String status = "pending";
        /** Tools this step may use */
        private List<String> tools;

        /** Target host IDs for this step */
        private List<String> hosts;
        /** Parallel group number — steps with the same group execute concurrently */
        private Integer parallelGroup;
        /** Hint for how to rollback this step on failure */
        private String rollbackHint;
        /** Step execution result summary */
        private String result;
        /** Error message if the step failed */
        private String error;

        // -- DAG workflow fields (Phase 3 Step 25) --

        /** Step indices this step depends on — forms the DAG edges */
        private List<Integer> dependsOn;
        /** Condition expression evaluated before running (e.g. "step[1].status == 'completed'") */
        private String condition;
        /** Whether this step is a human checkpoint requiring approval */
        private boolean checkpoint;
        /** Variable name to store step result for cross-step data passing */
        private String outputVar;
        /** Step-level timeout in seconds (null = use global default) */
        private Integer timeoutSec;
        /** Failure strategy: abort / skip / goto:{stepIndex} */
        private String onFailure;
        /** Input variable mappings: paramName → ${outputVarName} from previous steps */
        private Map<String, String> inputVars;
    }
}
